annotations:
  modified_by: nexclipper
apiVersion: v2
appVersion: 0.3.0
dependencies:
- condition: timescaledb-single.enabled
  name: timescaledb-single
  repository: https://nexclipper.github.io/helm-charts
  version: 0.8.2
- condition: promscale.enabled
  name: promscale
  repository: https://nexclipper.github.io/helm-charts
  version: 0.3.0
- condition: prometheus.enabled
  name: prometheus
  repository: https://nexclipper.github.io/helm-charts
  version: 13.3.3
- condition: grafana.enabled
  name: grafana
  repository: https://nexclipper.github.io/helm-charts
  version: 6.4.4
- condition: loki-stack.enabled
  name: loki-stack
  repository: https://nexclipper.github.io/helm-charts
  version: 2.3.1
description: NexClipper(0419v1) Helm chart for tobs included Loki
name: tobs
type: application
version: 0.3.0
