apiVersion: v2
name: tobs
description: A Helm chart for tobs, The Observability Stack for Kubernetes

type: application

version: 0.1.2
appVersion: 0.1.2

dependencies:
  - name: timescaledb-single
    condition: timescaledb-single.enabled
    version: 0.5.5
    repository: https://nexclipper.github.io/helm-charts
  - name: promscale
    condition: promscale.enabled
    version: 0.1.1
    repository: https://nexclipper.github.io/helm-charts
  - name: prometheus
    condition: prometheus.enabled
    version: 11.6.7
    repository: https://nexclipper.github.io/helm-charts
  - name: grafana
    condition: grafana.enabled
    version: 6.1.0
    repository: https://nexclipper.github.io/helm-charts
  - name: alertmanager
    condition: alertmanager.enabled
    version: 0.1.4
    repository: https://nexclipper.github.io/helm-charts
