apiVersion: v1
kind: Service
metadata:
  name: {{ include "connector.fullname" . | trunc 53 }}-connector
  labels:
    app: {{ template "connector.fullname" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ .Values.service.loadBalancer.annotations | toYaml | indent 4 }}
spec:
  selector:
    app: {{ template "connector.fullname" . }}
{{- if .Values.service.loadBalancer.enabled }}
  type: LoadBalancer
  ports:
  - name: connector-port
    port: {{ .Values.service.port }}
    protocol: TCP
{{- else if .Values.service.nodePort.enabled }}
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - name: connector-port
    port: {{ .Values.service.port }}
    protocol: TCP
    nodePort: {{ .Values.service.nodePort.port }}
{{- else }}
  type: ClusterIP
  ports:
  - name: connector-port
    port: {{ .Values.service.port }}
    protocol: TCP
{{- end }}
